version: '3'
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: xamlinx_app
    ports:
      - 80:80
      - 443:443
    container_name: xamlinx_app
    volumes:
       - ./app:/usr/src/app/app
       - /usr/src/app/app/node_modules
       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf