FROM node:lts-alpine

WORKDIR /usr/src/app/app

COPY package*.json ./

RUN npm install

##RUN npm install -g @angular/cli @angular-devkit/build-angular && npm install

EXPOSE 4200

CMD ["npm", "start"]
